# Generated by Django 5.1.6 on 2025-03-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_data_registro_remove_profile_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nome_publico',
        ),
    ]
