# Generated by Django 5.1.6 on 2025-03-25 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_topico_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.postagem'),
        ),
    ]
